import json
from pathlib import Path
from typing import Any

import torch
from torch import Tensor
from torch.utils.data import Dataset
from torchvision.io import ImageReadMode, read_image

from detgpt import FIGURES_DIR
from detgpt.lvis_api import default_manifest_path
from detgpt.visualize import save_detection_samples


class _LvisDataset(Dataset):
    """Dataset backed by a local manifest generated by the setup pipeline."""

    def __init__(self, manifest_path: Path) -> None:
        """Initialize the dataset.

        Args:
            manifest_path: Path to a JSON manifest file.
        """
        self.manifest_path = manifest_path
        with manifest_path.open("r", encoding="utf-8") as file_handle:
            self.samples: list[dict[str, Any]] = json.load(file_handle)

    def __len__(self) -> int:
        """Return the number of available samples."""
        return len(self.samples)

    def __getitem__(self, index: int) -> dict[str, Any]:
        """Return a single sample.

        Args:
            index: Sample index.

        Returns:
            Dictionary with local and remote image metadata.
        """
        return self.samples[index]


class Task1DetectionDataset(_LvisDataset):
    """Task 1 dataset wrapper that returns image tensors and detection targets.

    The dataset uses the prepared LVIS manifest and loads local images from
    ``local_path``. Each sample is returned in detector-friendly format:
    ``(image_tensor, target_dict)``.
    """

    def __init__(
        self,
        split: str = "train",
        transform: Any | None = None,
        to_float: bool = True,
    ) -> None:
        """Initialize Task 1 detection dataset.

        Args:
            split: LVIS split. One of ``train`` or ``val``.
            transform: Optional callable receiving ``(image, target)`` and returning transformed values.
            to_float: Convert loaded images from ``uint8`` to ``float32`` in ``[0, 1]``.
        """

        manifest_path = default_manifest_path(split)
        super().__init__(manifest_path=manifest_path)
        self.transform = transform
        self.to_float = to_float

    def _build_target(self, sample: dict[str, Any]) -> dict[str, Any]:
        """Build detection target dictionary for a manifest sample.

        Args:
            sample: Single manifest entry.

        Returns:
            Target dictionary compatible with standard PyTorch detection models.
        """
        annotations = sample.get("annotations", [])

        boxes_xywh_centered = [self._extract_bbox_xcycwh(annotation) for annotation in annotations]
        labels = [int(annotation["category_id"]) for annotation in annotations]
        areas = [float(annotation.get("area", 0.0) or 0.0) for annotation in annotations]
        annotation_ids = [int(annotation["annotation_id"]) for annotation in annotations]

        if boxes_xywh_centered:
            boxes_tensor = torch.tensor(boxes_xywh_centered, dtype=torch.float32)
            labels_tensor = torch.tensor(labels, dtype=torch.int64)
            area_tensor = torch.tensor(areas, dtype=torch.float32)
            iscrowd_tensor = torch.zeros((len(boxes_xywh_centered),), dtype=torch.int64)
            annotation_ids_tensor = torch.tensor(annotation_ids, dtype=torch.int64)
        else:
            boxes_tensor = torch.zeros((0, 4), dtype=torch.float32)
            labels_tensor = torch.zeros((0,), dtype=torch.int64)
            area_tensor = torch.zeros((0,), dtype=torch.float32)
            iscrowd_tensor = torch.zeros((0,), dtype=torch.int64)
            annotation_ids_tensor = torch.zeros((0,), dtype=torch.int64)

        return {
            "boxes": boxes_tensor,
            "labels": labels_tensor,
            "area": area_tensor,
            "iscrowd": iscrowd_tensor,
            "annotation_ids": annotation_ids_tensor,
            "image_id": torch.tensor([int(sample["image_id"])], dtype=torch.int64),
            "category_names": [annotation.get("category_name", "") for annotation in annotations],
        }

    @staticmethod
    def _extract_bbox_xcycwh(annotation: dict[str, Any]) -> list[float]:
        """Extract center-format bbox as list ``[x_center, y_center, width, height]``."""
        bbox = annotation.get("bbox_xywh_centered", [0.0, 0.0, 0.0, 0.0])
        if isinstance(bbox, dict):
            return [
                float(bbox.get("x_center", 0.0)),
                float(bbox.get("y_center", 0.0)),
                float(bbox.get("width", 0.0)),
                float(bbox.get("height", 0.0)),
            ]
        if isinstance(bbox, list) and len(bbox) == 4:
            return [float(value) for value in bbox]
        return [0.0, 0.0, 0.0, 0.0]

    def __getitem__(self, index: int) -> tuple[Tensor, dict[str, Any]]:
        """Load image tensor and detection target.

        Args:
            index: Sample index.

        Returns:
            Tuple ``(image, target)`` where ``image`` is ``C x H x W``.
        """
        sample = super().__getitem__(index)
        raw_local_path = sample.get("local_path")
        if not raw_local_path:
            raise ValueError(
                f"Sample {sample.get('image_id')} has no usable 'local_path' in the manifest."
            )
        local_path = Path(raw_local_path)
        if not local_path.is_file():
            raise FileNotFoundError(
                f"Image file not found or not a file for sample {sample.get('image_id')}: {local_path}"
            )

        image = read_image(str(local_path), mode=ImageReadMode.RGB)
        if self.to_float:
            image = image.to(dtype=torch.float32) / 255.0

        target = self._build_target(sample)
        if self.transform is not None:
            image, target = self.transform(image, target)

        return image, target


def task1_collate_fn(batch: list[tuple[Tensor, dict[str, Any]]]) -> tuple[list[Tensor], list[dict[str, Any]]]:
    """Collate function for Task 1 detection batches.

    Args:
        batch: List of ``(image, target)`` samples.

    Returns:
        Tuple ``(images, targets)`` with variable-size targets preserved.
    """
    images, targets = zip(*batch, strict=True)
    return list(images), list(targets)


if __name__ == "__main__":
    dataset = Task1DetectionDataset(split="train")
    save_detection_samples(dataset=dataset, output_dir=FIGURES_DIR, num_samples=5)
